// Flare icon library — a curated set of semantic icon names shared across all
// four platforms. Each platform maps the SAME name to its native glyph source
// (Web → Lucide via ./icon-glyphs, iOS → SF Symbols, Flutter/Android → Material Icons).
// Consumers use `<FlareIcon name="search" />` instead of importing icons directly.
import type { Component } from "vue";
import {
  SearchOutline,
  SendOutline,
  EllipsisHorizontal,
  ArrowBackOutline,
  CloseOutline,
  CheckmarkOutline,
  AddOutline,
  RemoveOutline,
  CreateOutline,
  TrashOutline,
  HeartOutline,
  Heart,
  ChatbubbleOutline,
  ChatbubblesOutline,
  PlanetOutline,
  ShareSocialOutline,
  CameraOutline,
  ImageOutline,
  LocationOutline,
  MicOutline,
  CallOutline,
  VideocamOutline,
  SettingsOutline,
  PersonOutline,
  PeopleOutline,
  PersonAddOutline,
  StarOutline,
  BookmarkOutline,
  DownloadOutline,
  LinkOutline,
  HappyOutline,
  DocumentOutline,
  FolderOutline,
  NotificationsOutline,
  NotificationsOffOutline,
  CopyOutline,
  ArrowRedoOutline,
  ArrowUndoOutline,
  RefreshOutline,
  ChevronDownOutline,
  ChevronForwardOutline,
  ArrowDownOutline,
  WarningOutline,
  InformationCircleOutline,
  CheckmarkCircleOutline,
  CloseCircleOutline,
  CalendarOutline,
  TimeOutline,
  EyeOutline,
  EyeOffOutline,
  LockClosedOutline,
  QrCodeOutline,
} from "./icon-glyphs";

/** The canonical Flare icon name set (single source; native maps the same keys). */
export const flareIcons = {
  search: SearchOutline,
  send: SendOutline,
  more: EllipsisHorizontal,
  back: ArrowBackOutline,
  close: CloseOutline,
  check: CheckmarkOutline,
  add: AddOutline,
  remove: RemoveOutline,
  edit: CreateOutline,
  delete: TrashOutline,
  heart: HeartOutline,
  "heart-filled": Heart,
  comment: ChatbubbleOutline,
  chats: ChatbubblesOutline,
  moments: PlanetOutline,
  share: ShareSocialOutline,
  camera: CameraOutline,
  image: ImageOutline,
  location: LocationOutline,
  mic: MicOutline,
  phone: CallOutline,
  video: VideocamOutline,
  settings: SettingsOutline,
  person: PersonOutline,
  people: PeopleOutline,
  "person-add": PersonAddOutline,
  star: StarOutline,
  bookmark: BookmarkOutline,
  download: DownloadOutline,
  link: LinkOutline,
  emoji: HappyOutline,
  file: DocumentOutline,
  folder: FolderOutline,
  notification: NotificationsOutline,
  mute: NotificationsOffOutline,
  copy: CopyOutline,
  forward: ArrowRedoOutline,
  reply: ArrowUndoOutline,
  refresh: RefreshOutline,
  "chevron-down": ChevronDownOutline,
  "chevron-right": ChevronForwardOutline,
  "arrow-down": ArrowDownOutline,
  warning: WarningOutline,
  info: InformationCircleOutline,
  success: CheckmarkCircleOutline,
  error: CloseCircleOutline,
  calendar: CalendarOutline,
  clock: TimeOutline,
  eye: EyeOutline,
  "eye-off": EyeOffOutline,
  lock: LockClosedOutline,
  qr: QrCodeOutline,
} satisfies Record<string, Component>;

export type FlareIconName = keyof typeof flareIcons;
export const flareIconNames = Object.keys(flareIcons) as FlareIconName[];
