<script setup lang="ts">
import { nextTick, ref, watch } from "vue";
import { NButton, NInput, NModal, NSelect } from "naive-ui";

const open = defineModel<boolean>("open", { default: false });
const peerUserId = defineModel<string>("peerUserId", { default: "" });
const conversationType = defineModel<"single" | "group">("conversationType", { default: "single" });

defineProps<{
  busy?: boolean;
}>();

const emit = defineEmits<{
  (event: "confirm"): void;
}>();

const peerInputRef = ref<InstanceType<typeof NInput> | null>(null);

watch(open, (visible) => {
  if (!visible) return;
  void nextTick(() => {
    peerInputRef.value?.focus();
  });
});

function closeDialog(): void {
  open.value = false;
}

function submitDialog(): void {
  if (!peerUserId.value.trim()) return;
  emit("confirm");
}
</script>

<template>
  <n-modal
    v-model:show="open"
    preset="card"
    title="Open conversation"
    class="start-dialog-modal"
    :auto-focus="false"
    :trap-focus="true"
    :mask-closable="true"
    style="max-width: 420px"
    @after-enter="() => peerInputRef?.focus()"
  >
    <div class="start-dialog-field">
      <span>{{ conversationType === "group" ? "Member ID" : "User ID" }}</span>
      <n-input
        ref="peerInputRef"
        v-model:value="peerUserId"
        size="large"
        clearable
        :placeholder="conversationType === 'group' ? 'Enter member userIds, separated by comma or space' : 'Enter the user's real userId'"
        @keydown.enter.prevent="submitDialog"
      />
      <small class="start-dialog-hint">
        {{
          conversationType === "group"
            ? "Group conversation is generated by SDK via getGroupConversationByUserIds from the member list"
            : "Conversation ID is generated automatically by SDK via getOneConversation"
        }}
      </small>
    </div>
    <div class="start-dialog-field">
      <span>Conversation type</span>
      <n-select
        v-model:value="conversationType"
        :options="[
          { label: 'Direct', value: 'single' },
          { label: 'Group', value: 'group' },
        ]"
      />
    </div>
    <template #action>
      <n-button text @click="closeDialog">Cancel</n-button>
      <n-button type="primary" :loading="busy" :disabled="!peerUserId.trim()" @click="submitDialog">
        Open
      </n-button>
    </template>
  </n-modal>
</template>
