// AUTO-GENERATED by scripts/gen-icon-shim.mjs — do not edit by hand.
// Drop-in shim: re-exports the ionicons5 names the kit uses, each backed by a
// Lucide glyph (thin-line / Feishu style). This is the single seam that swaps
// the kit's web icon set — all components import their icons from here instead
// of "@vicons/ionicons5", so call sites never change.
//
// Each export is a functional component sized to 1em so naive-ui <n-icon>'s
// font-size sizing keeps working, and inheriting currentColor. To change the
// mapping or add an icon, edit MAP in scripts/gen-icon-shim.mjs and re-run it.
//
// The drawn SVG names its glyph in data-flare-glyph (the Lucide name). A screenshot compared with an
// anti-aliasing tolerance cannot see one 18 px glyph swapped for another (FR-136); a list of the glyph
// names on the page can, so application tests record one beside each screenshot.
import { h, type Component, type FunctionalComponent } from "vue";
import {
  Archive as LuArchive,
  ArchiveRestore as LuArchiveRestore,
  ArrowDown as LuArrowDown,
  ArrowLeft as LuArrowLeft,
  AtSign as LuAtSign,
  Ban as LuBan,
  Bell as LuBell,
  BellOff as LuBellOff,
  Bookmark as LuBookmark,
  Bug as LuBug,
  Calendar as LuCalendar,
  Camera as LuCamera,
  ChartColumn as LuChartColumn,
  Check as LuCheck,
  CheckCheck as LuCheckCheck,
  ChevronDown as LuChevronDown,
  ChevronLeft as LuChevronLeft,
  ChevronRight as LuChevronRight,
  ChevronUp as LuChevronUp,
  CircleAlert as LuCircleAlert,
  CircleCheck as LuCircleCheck,
  CirclePlay as LuCirclePlay,
  CirclePlus as LuCirclePlus,
  CircleX as LuCircleX,
  Clock as LuClock,
  CloudCheck as LuCloudCheck,
  CloudDownload as LuCloudDownload,
  Code as LuCode,
  CodeXml as LuCodeXml,
  Compass as LuCompass,
  Contact as LuContact,
  Copy as LuCopy,
  CornerDownLeft as LuCornerDownLeft,
  Crop as LuCrop,
  Download as LuDownload,
  Earth as LuEarth,
  Ellipsis as LuEllipsis,
  Eraser as LuEraser,
  Expand as LuExpand,
  Eye as LuEye,
  EyeOff as LuEyeOff,
  FaceSlightlySmiling as LuFaceSlightlySmiling,
  FaceSlightlySmilingPlus as LuFaceSlightlySmilingPlus,
  File as LuFile,
  FileText as LuFileText,
  Flag as LuFlag,
  Flame as LuFlame,
  FlaskConical as LuFlaskConical,
  Folder as LuFolder,
  FolderOpen as LuFolderOpen,
  Forward as LuForward,
  Gift as LuGift,
  Globe as LuGlobe,
  HardDrive as LuHardDrive,
  Hash as LuHash,
  Heart as LuHeart,
  HeartOff as LuHeartOff,
  Image as LuImage,
  Inbox as LuInbox,
  Info as LuInfo,
  KeyRound as LuKeyRound,
  Keyboard as LuKeyboard,
  Languages as LuLanguages,
  LayoutGrid as LuLayoutGrid,
  Library as LuLibrary,
  Link as LuLink,
  List as LuList,
  ListChecks as LuListChecks,
  ListOrdered as LuListOrdered,
  Lock as LuLock,
  LogIn as LuLogIn,
  LogOut as LuLogOut,
  Mail as LuMail,
  MailOpen as LuMailOpen,
  MapPin as LuMapPin,
  Megaphone as LuMegaphone,
  Merge as LuMerge,
  MessageCircle as LuMessageCircle,
  MessageCircleMore as LuMessageCircleMore,
  MessageSquareDot as LuMessageSquareDot,
  MessageSquareOff as LuMessageSquareOff,
  MessagesSquare as LuMessagesSquare,
  Mic as LuMic,
  MicOff as LuMicOff,
  Minus as LuMinus,
  MonitorSmartphone as LuMonitorSmartphone,
  Moon as LuMoon,
  Navigation as LuNavigation,
  OctagonAlert as LuOctagonAlert,
  Paperclip as LuPaperclip,
  Pause as LuPause,
  Pencil as LuPencil,
  Phone as LuPhone,
  PhoneOff as LuPhoneOff,
  Pin as LuPin,
  PinOff as LuPinOff,
  Play as LuPlay,
  Plus as LuPlus,
  QrCode as LuQrCode,
  Quote as LuQuote,
  RefreshCw as LuRefreshCw,
  Reply as LuReply,
  RotateCw as LuRotateCw,
  ScreenShare as LuScreenShare,
  Search as LuSearch,
  Send as LuSend,
  Settings as LuSettings,
  Share2 as LuShare2,
  ShieldCheck as LuShieldCheck,
  Shrink as LuShrink,
  SkipBack as LuSkipBack,
  SkipForward as LuSkipForward,
  Sparkles as LuSparkles,
  SquareCheck as LuSquareCheck,
  Star as LuStar,
  SwitchCamera as LuSwitchCamera,
  Tag as LuTag,
  Terminal as LuTerminal,
  ThumbsUp as LuThumbsUp,
  Trash as LuTrash,
  TriangleAlert as LuTriangleAlert,
  Type as LuType,
  Undo2 as LuUndo2,
  User as LuUser,
  UserMinus as LuUserMinus,
  UserPlus as LuUserPlus,
  Users as LuUsers,
  UsersRound as LuUsersRound,
  Video as LuVideo,
  VideoOff as LuVideoOff,
  Volume2 as LuVolume2,
  VolumeX as LuVolumeX,
  Vote as LuVote,
  Wifi as LuWifi,
  X as LuX,
  Zap as LuZap,
  ZoomIn as LuZoomIn,
  ZoomOut as LuZoomOut,
} from "@lucide/vue";

// 具名导入而不是 `import * as lucide`：命名空间导入会让打包器无法 tree-shake，
// 整个 Lucide（近 900 KiB）都会进产物，而这里实际只用到一百来个图标。
const REGISTRY: Record<string, Component> = {
  Archive: LuArchive,
  ArchiveRestore: LuArchiveRestore,
  ArrowDown: LuArrowDown,
  ArrowLeft: LuArrowLeft,
  AtSign: LuAtSign,
  Ban: LuBan,
  Bell: LuBell,
  BellOff: LuBellOff,
  Bookmark: LuBookmark,
  Bug: LuBug,
  Calendar: LuCalendar,
  Camera: LuCamera,
  ChartColumn: LuChartColumn,
  Check: LuCheck,
  CheckCheck: LuCheckCheck,
  ChevronDown: LuChevronDown,
  ChevronLeft: LuChevronLeft,
  ChevronRight: LuChevronRight,
  ChevronUp: LuChevronUp,
  CircleAlert: LuCircleAlert,
  CircleCheck: LuCircleCheck,
  CirclePlay: LuCirclePlay,
  CirclePlus: LuCirclePlus,
  CircleX: LuCircleX,
  Clock: LuClock,
  CloudCheck: LuCloudCheck,
  CloudDownload: LuCloudDownload,
  Code: LuCode,
  CodeXml: LuCodeXml,
  Compass: LuCompass,
  Contact: LuContact,
  Copy: LuCopy,
  CornerDownLeft: LuCornerDownLeft,
  Crop: LuCrop,
  Download: LuDownload,
  Earth: LuEarth,
  Ellipsis: LuEllipsis,
  Eraser: LuEraser,
  Expand: LuExpand,
  Eye: LuEye,
  EyeOff: LuEyeOff,
  FaceSlightlySmiling: LuFaceSlightlySmiling,
  FaceSlightlySmilingPlus: LuFaceSlightlySmilingPlus,
  File: LuFile,
  FileText: LuFileText,
  Flag: LuFlag,
  Flame: LuFlame,
  FlaskConical: LuFlaskConical,
  Folder: LuFolder,
  FolderOpen: LuFolderOpen,
  Forward: LuForward,
  Gift: LuGift,
  Globe: LuGlobe,
  HardDrive: LuHardDrive,
  Hash: LuHash,
  Heart: LuHeart,
  HeartOff: LuHeartOff,
  Image: LuImage,
  Inbox: LuInbox,
  Info: LuInfo,
  KeyRound: LuKeyRound,
  Keyboard: LuKeyboard,
  Languages: LuLanguages,
  LayoutGrid: LuLayoutGrid,
  Library: LuLibrary,
  Link: LuLink,
  List: LuList,
  ListChecks: LuListChecks,
  ListOrdered: LuListOrdered,
  Lock: LuLock,
  LogIn: LuLogIn,
  LogOut: LuLogOut,
  Mail: LuMail,
  MailOpen: LuMailOpen,
  MapPin: LuMapPin,
  Megaphone: LuMegaphone,
  Merge: LuMerge,
  MessageCircle: LuMessageCircle,
  MessageCircleMore: LuMessageCircleMore,
  MessageSquareDot: LuMessageSquareDot,
  MessageSquareOff: LuMessageSquareOff,
  MessagesSquare: LuMessagesSquare,
  Mic: LuMic,
  MicOff: LuMicOff,
  Minus: LuMinus,
  MonitorSmartphone: LuMonitorSmartphone,
  Moon: LuMoon,
  Navigation: LuNavigation,
  OctagonAlert: LuOctagonAlert,
  Paperclip: LuPaperclip,
  Pause: LuPause,
  Pencil: LuPencil,
  Phone: LuPhone,
  PhoneOff: LuPhoneOff,
  Pin: LuPin,
  PinOff: LuPinOff,
  Play: LuPlay,
  Plus: LuPlus,
  QrCode: LuQrCode,
  Quote: LuQuote,
  RefreshCw: LuRefreshCw,
  Reply: LuReply,
  RotateCw: LuRotateCw,
  ScreenShare: LuScreenShare,
  Search: LuSearch,
  Send: LuSend,
  Settings: LuSettings,
  Share2: LuShare2,
  ShieldCheck: LuShieldCheck,
  Shrink: LuShrink,
  SkipBack: LuSkipBack,
  SkipForward: LuSkipForward,
  Sparkles: LuSparkles,
  SquareCheck: LuSquareCheck,
  Star: LuStar,
  SwitchCamera: LuSwitchCamera,
  Tag: LuTag,
  Terminal: LuTerminal,
  ThumbsUp: LuThumbsUp,
  Trash: LuTrash,
  TriangleAlert: LuTriangleAlert,
  Type: LuType,
  Undo2: LuUndo2,
  User: LuUser,
  UserMinus: LuUserMinus,
  UserPlus: LuUserPlus,
  Users: LuUsers,
  UsersRound: LuUsersRound,
  Video: LuVideo,
  VideoOff: LuVideoOff,
  Volume2: LuVolume2,
  VolumeX: LuVolumeX,
  Vote: LuVote,
  Wifi: LuWifi,
  X: LuX,
  Zap: LuZap,
  ZoomIn: LuZoomIn,
  ZoomOut: LuZoomOut,
};

const STROKE = 1.75;
function glyph(name: string, filled = false): FunctionalComponent {
  const Lucide = REGISTRY[name];
  const C: FunctionalComponent = (_props, { attrs }) =>
    h(Lucide, { size: "1em", "stroke-width": STROKE, "data-flare-glyph": name, ...(filled ? { fill: "currentColor" } : {}), ...attrs });
  (C as { displayName?: string }).displayName = name;
  return C;
}

export const AddCircleOutline = /*#__PURE__*/ glyph("CirclePlus");
export const AddOutline = /*#__PURE__*/ glyph("Plus");
export const AlertCircleOutline = /*#__PURE__*/ glyph("CircleAlert");
export const AppsOutline = /*#__PURE__*/ glyph("LayoutGrid");
export const ArchiveOutline = /*#__PURE__*/ glyph("Archive");
export const ArrowBackOutline = /*#__PURE__*/ glyph("ArrowLeft");
export const ArrowDownOutline = /*#__PURE__*/ glyph("ArrowDown");
export const ArrowRedoOutline = /*#__PURE__*/ glyph("Forward");
export const ArrowUndoOutline = /*#__PURE__*/ glyph("Reply");
export const AtOutline = /*#__PURE__*/ glyph("AtSign");
export const BanOutline = /*#__PURE__*/ glyph("Ban");
export const BookmarkOutline = /*#__PURE__*/ glyph("Bookmark");
export const CalendarOutline = /*#__PURE__*/ glyph("Calendar");
export const CallOutline = /*#__PURE__*/ glyph("Phone");
export const CameraOutline = /*#__PURE__*/ glyph("Camera");
export const CameraReverseOutline = /*#__PURE__*/ glyph("SwitchCamera");
export const ChatbubbleEllipsesOutline = /*#__PURE__*/ glyph("MessageCircleMore");
export const ChatbubbleOutline = /*#__PURE__*/ glyph("MessageCircle");
export const ChatbubblesOutline = /*#__PURE__*/ glyph("MessagesSquare");
export const CheckboxOutline = /*#__PURE__*/ glyph("SquareCheck");
export const CheckmarkCircle = /*#__PURE__*/ glyph("CircleCheck", true);
export const CheckmarkCircleOutline = /*#__PURE__*/ glyph("CircleCheck");
export const CheckmarkDoneOutline = /*#__PURE__*/ glyph("CheckCheck");
export const CheckmarkOutline = /*#__PURE__*/ glyph("Check");
export const ChevronBackOutline = /*#__PURE__*/ glyph("ChevronLeft");
export const ChevronDownOutline = /*#__PURE__*/ glyph("ChevronDown");
export const ChevronForwardOutline = /*#__PURE__*/ glyph("ChevronRight");
export const ChevronUpOutline = /*#__PURE__*/ glyph("ChevronUp");
export const CloseCircle = /*#__PURE__*/ glyph("CircleX", true);
export const CloseCircleOutline = /*#__PURE__*/ glyph("CircleX");
export const CloseOutline = /*#__PURE__*/ glyph("X");
export const CloudDoneOutline = /*#__PURE__*/ glyph("CloudCheck");
export const CloudDownloadOutline = /*#__PURE__*/ glyph("CloudDownload");
export const CodeSlashOutline = /*#__PURE__*/ glyph("Code");
export const CodeWorkingOutline = /*#__PURE__*/ glyph("CodeXml");
export const ContractOutline = /*#__PURE__*/ glyph("Shrink");
export const CopyOutline = /*#__PURE__*/ glyph("Copy");
export const CreateOutline = /*#__PURE__*/ glyph("Pencil");
export const DocumentOutline = /*#__PURE__*/ glyph("File");
export const DocumentTextOutline = /*#__PURE__*/ glyph("FileText");
export const DownloadOutline = /*#__PURE__*/ glyph("Download");
export const EarthOutline = /*#__PURE__*/ glyph("Earth");
export const EllipsisHorizontal = /*#__PURE__*/ glyph("Ellipsis");
export const EllipsisHorizontalOutline = /*#__PURE__*/ glyph("Ellipsis");
export const ExpandOutline = /*#__PURE__*/ glyph("Expand");
export const EyeOffOutline = /*#__PURE__*/ glyph("EyeOff");
export const EyeOutline = /*#__PURE__*/ glyph("Eye");
export const FileTrayOutline = /*#__PURE__*/ glyph("Inbox");
export const FlagOutline = /*#__PURE__*/ glyph("Flag");
export const FlashOutline = /*#__PURE__*/ glyph("Zap");
export const FlaskOutline = /*#__PURE__*/ glyph("FlaskConical");
export const FolderOpenOutline = /*#__PURE__*/ glyph("FolderOpen");
export const FolderOutline = /*#__PURE__*/ glyph("Folder");
export const GiftOutline = /*#__PURE__*/ glyph("Gift");
export const HappyOutline = /*#__PURE__*/ glyph("FaceSlightlySmiling");
export const Heart = /*#__PURE__*/ glyph("Heart", true);
export const HeartDislikeOutline = /*#__PURE__*/ glyph("HeartOff");
export const HeartOutline = /*#__PURE__*/ glyph("Heart");
export const ImageOutline = /*#__PURE__*/ glyph("Image");
export const InformationCircle = /*#__PURE__*/ glyph("Info", true);
export const InformationCircleOutline = /*#__PURE__*/ glyph("Info");
export const LanguageOutline = /*#__PURE__*/ glyph("Languages");
export const LibraryOutline = /*#__PURE__*/ glyph("Library");
export const LinkOutline = /*#__PURE__*/ glyph("Link");
export const ListOutline = /*#__PURE__*/ glyph("List");
export const LocationOutline = /*#__PURE__*/ glyph("MapPin");
export const LockClosedOutline = /*#__PURE__*/ glyph("Lock");
export const LogInOutline = /*#__PURE__*/ glyph("LogIn");
export const LogOutOutline = /*#__PURE__*/ glyph("LogOut");
export const MailUnreadOutline = /*#__PURE__*/ glyph("MailOpen");
export const MegaphoneOutline = /*#__PURE__*/ glyph("Megaphone");
export const MicOffOutline = /*#__PURE__*/ glyph("MicOff");
export const MicOutline = /*#__PURE__*/ glyph("Mic");
export const MoonOutline = /*#__PURE__*/ glyph("Moon");
export const PricetagOutline = /*#__PURE__*/ glyph("Tag");
export const PhonePortraitOutline = /*#__PURE__*/ glyph("MonitorSmartphone");
export const NotificationsOffOutline = /*#__PURE__*/ glyph("BellOff");
export const NotificationsOutline = /*#__PURE__*/ glyph("Bell");
export const PauseOutline = /*#__PURE__*/ glyph("Pause");
export const PeopleOutline = /*#__PURE__*/ glyph("Users");
export const PersonAddOutline = /*#__PURE__*/ glyph("UserPlus");
export const PersonOutline = /*#__PURE__*/ glyph("User");
export const PinOutline = /*#__PURE__*/ glyph("Pin");
export const PlanetOutline = /*#__PURE__*/ glyph("Compass");
export const PlayCircleOutline = /*#__PURE__*/ glyph("CirclePlay");
export const PlayOutline = /*#__PURE__*/ glyph("Play");
export const QrCodeOutline = /*#__PURE__*/ glyph("QrCode");
export const ReaderOutline = /*#__PURE__*/ glyph("Quote");
export const RefreshOutline = /*#__PURE__*/ glyph("RefreshCw");
export const RemoveOutline = /*#__PURE__*/ glyph("Minus");
export const ReorderThreeOutline = /*#__PURE__*/ glyph("ListOrdered");
export const ReturnUpBackOutline = /*#__PURE__*/ glyph("Reply");
export const SearchOutline = /*#__PURE__*/ glyph("Search");
export const SendOutline = /*#__PURE__*/ glyph("Send");
export const SettingsOutline = /*#__PURE__*/ glyph("Settings");
export const ShareSocialOutline = /*#__PURE__*/ glyph("Share2");
export const Star = /*#__PURE__*/ glyph("Star", true);
export const StarOutline = /*#__PURE__*/ glyph("Star");
export const SyncOutline = /*#__PURE__*/ glyph("RefreshCw");
export const TerminalOutline = /*#__PURE__*/ glyph("Terminal");
export const TextOutline = /*#__PURE__*/ glyph("Type");
export const ThumbsUpOutline = /*#__PURE__*/ glyph("ThumbsUp");
export const TimeOutline = /*#__PURE__*/ glyph("Clock");
export const TrashOutline = /*#__PURE__*/ glyph("Trash");
export const VideocamOffOutline = /*#__PURE__*/ glyph("VideoOff");
export const VideocamOutline = /*#__PURE__*/ glyph("Video");
export const VolumeHighOutline = /*#__PURE__*/ glyph("Volume2");
export const VolumeMuteOutline = /*#__PURE__*/ glyph("VolumeX");
export const WarningOutline = /*#__PURE__*/ glyph("TriangleAlert");
export const AlertCircle = /*#__PURE__*/ glyph("CircleAlert", true);
export const CropOutline = /*#__PURE__*/ glyph("Crop");
export const DocumentAttachOutline = /*#__PURE__*/ glyph("Paperclip");
export const Flame = /*#__PURE__*/ glyph("Flame", true);
export const FlameOutline = /*#__PURE__*/ glyph("Flame");
export const MailOutline = /*#__PURE__*/ glyph("Mail");
export const NavigateOutline = /*#__PURE__*/ glyph("Navigation");
export const PeopleCircleOutline = /*#__PURE__*/ glyph("UsersRound");
export const PlaySkipBackOutline = /*#__PURE__*/ glyph("SkipBack");
export const PlaySkipForwardOutline = /*#__PURE__*/ glyph("SkipForward");
export const ReorderFourOutline = /*#__PURE__*/ glyph("List");
export const ReturnDownBackOutline = /*#__PURE__*/ glyph("CornerDownLeft");
export const ShieldCheckmarkOutline = /*#__PURE__*/ glyph("ShieldCheck");
export const SparklesOutline = /*#__PURE__*/ glyph("Sparkles");
export const Time = /*#__PURE__*/ glyph("Clock", true);
export const WifiOutline = /*#__PURE__*/ glyph("Wifi");
export const PodiumOutline = /*#__PURE__*/ glyph("Vote");
export const AddReactionOutline = /*#__PURE__*/ glyph("FaceSlightlySmilingPlus");
export const AlertOctagonOutline = /*#__PURE__*/ glyph("OctagonAlert");
export const ArchiveRestoreOutline = /*#__PURE__*/ glyph("ArchiveRestore");
export const BarChartOutline = /*#__PURE__*/ glyph("ChartColumn");
export const CallEndOutline = /*#__PURE__*/ glyph("PhoneOff");
export const ChatbubbleDotOutline = /*#__PURE__*/ glyph("MessageSquareDot");
export const ChatbubbleOffOutline = /*#__PURE__*/ glyph("MessageSquareOff");
export const ChecklistOutline = /*#__PURE__*/ glyph("ListChecks");
export const EraserOutline = /*#__PURE__*/ glyph("Eraser");
export const GitMergeOutline = /*#__PURE__*/ glyph("Merge");
export const GlobeOutline = /*#__PURE__*/ glyph("Globe");
export const KeyOutline = /*#__PURE__*/ glyph("KeyRound");
export const KeyboardOutline = /*#__PURE__*/ glyph("Keyboard");
export const PersonRemoveOutline = /*#__PURE__*/ glyph("UserMinus");
export const PinOffOutline = /*#__PURE__*/ glyph("PinOff");
export const RotateOutline = /*#__PURE__*/ glyph("RotateCw");
export const ScreenShareOutline = /*#__PURE__*/ glyph("ScreenShare");
export const UndoOutline = /*#__PURE__*/ glyph("Undo2");
export const ZoomInOutline = /*#__PURE__*/ glyph("ZoomIn");
export const ZoomOutOutline = /*#__PURE__*/ glyph("ZoomOut");
export const BugOutline = /*#__PURE__*/ glyph("Bug");
export const HashOutline = /*#__PURE__*/ glyph("Hash");
export const IdCardOutline = /*#__PURE__*/ glyph("Contact");
export const ServerOutline = /*#__PURE__*/ glyph("HardDrive");
