// Flare icon library — a curated set of semantic icon names shared across all
// four platforms. Each platform maps the SAME name to its native glyph source
// (Web → Lucide via ./icon-glyphs, iOS → SF Symbols, Flutter/Android → Material Icons).
// Consumers use `<FlareIcon name="search" />` instead of importing icons directly.
import type { Component } from "vue";
import {
  SearchOutline,
  SendOutline,
  EllipsisHorizontal,
  ArrowBackOutline,
  CloseOutline,
  CheckmarkOutline,
  AddOutline,
  RemoveOutline,
  CreateOutline,
  TrashOutline,
  HeartOutline,
  ChatbubbleOutline,
  ChatbubblesOutline,
  PlanetOutline,
  ShareSocialOutline,
  CameraOutline,
  ImageOutline,
  LocationOutline,
  MicOutline,
  CallOutline,
  VideocamOutline,
  SettingsOutline,
  PersonOutline,
  PeopleOutline,
  PersonAddOutline,
  StarOutline,
  DownloadOutline,
  LinkOutline,
  HappyOutline,
  DocumentOutline,
  FolderOutline,
  NotificationsOutline,
  NotificationsOffOutline,
  CopyOutline,
  ArrowRedoOutline,
  ArrowUndoOutline,
  RefreshOutline,
  ChevronDownOutline,
  ChevronForwardOutline,
  ArrowDownOutline,
  WarningOutline,
  InformationCircleOutline,
  CheckmarkCircleOutline,
  CalendarOutline,
  TimeOutline,
  EyeOutline,
  EyeOffOutline,
  LockClosedOutline,
  QrCodeOutline,
  BanOutline,
  PricetagOutline,
  MegaphoneOutline,
  MoonOutline,
  LanguageOutline,
  PhonePortraitOutline,
  LogOutOutline,
  PinOutline,
  UndoOutline,
  PinOffOutline,
  GitMergeOutline,
  ChecklistOutline,
  ReaderOutline,
  AddReactionOutline,
  AtOutline,
  CheckmarkDoneOutline,
  FlagOutline,
  TextOutline,
  DocumentAttachOutline,
  ChatbubbleDotOutline,
  ArchiveOutline,
  ArchiveRestoreOutline,
  EraserOutline,
  MicOffOutline,
  VideocamOffOutline,
  VolumeHighOutline,
  VolumeMuteOutline,
  CallEndOutline,
  CameraReverseOutline,
  ScreenShareOutline,
  PlayOutline,
  PauseOutline,
  ExpandOutline,
  ContractOutline,
  ZoomInOutline,
  ZoomOutOutline,
  RotateOutline,
  PeopleCircleOutline,
  ShieldCheckmarkOutline,
  PersonRemoveOutline,
  KeyOutline,
  ChatbubbleOffOutline,
  AlertOctagonOutline,
  ChevronUpOutline,
  ChevronBackOutline,
  KeyboardOutline,
  AppsOutline,
  AlertCircleOutline,
  BarChartOutline,
  GlobeOutline,
  BookmarkOutline,
  BugOutline,
  IdCardOutline,
  HashOutline,
  FileTrayOutline,
  ServerOutline,
} from "./icon-glyphs";

/** The canonical Flare icon name set (single source; native maps the same keys). */
export const flareIcons = {
  search: SearchOutline,
  send: SendOutline,
  more: EllipsisHorizontal,
  back: ArrowBackOutline,
  close: CloseOutline,
  check: CheckmarkOutline,
  add: AddOutline,
  remove: RemoveOutline,
  edit: CreateOutline,
  delete: TrashOutline,
  heart: HeartOutline,
  comment: ChatbubbleOutline,
  chats: ChatbubblesOutline,
  moments: PlanetOutline,
  share: ShareSocialOutline,
  camera: CameraOutline,
  image: ImageOutline,
  location: LocationOutline,
  mic: MicOutline,
  phone: CallOutline,
  video: VideocamOutline,
  settings: SettingsOutline,
  person: PersonOutline,
  people: PeopleOutline,
  "person-add": PersonAddOutline,
  star: StarOutline,
  download: DownloadOutline,
  link: LinkOutline,
  emoji: HappyOutline,
  file: DocumentOutline,
  folder: FolderOutline,
  notification: NotificationsOutline,
  mute: NotificationsOffOutline,
  copy: CopyOutline,
  forward: ArrowRedoOutline,
  reply: ArrowUndoOutline,
  refresh: RefreshOutline,
  "chevron-down": ChevronDownOutline,
  "chevron-right": ChevronForwardOutline,
  "arrow-down": ArrowDownOutline,
  warning: WarningOutline,
  info: InformationCircleOutline,
  success: CheckmarkCircleOutline,
  error: AlertCircleOutline,
  calendar: CalendarOutline,
  clock: TimeOutline,
  eye: EyeOutline,
  "eye-off": EyeOffOutline,
  lock: LockClosedOutline,
  qr: QrCodeOutline,
  block: BanOutline,
  tag: PricetagOutline,
  announcement: MegaphoneOutline,
  theme: MoonOutline,
  language: GlobeOutline,
  devices: PhonePortraitOutline,
  logout: LogOutOutline,
  pin: PinOutline,
  poll: BarChartOutline,
  recall: UndoOutline,
  unpin: PinOffOutline,
  "merge-forward": GitMergeOutline,
  "multi-select": ChecklistOutline,
  quote: ReaderOutline,
  reaction: AddReactionOutline,
  translate: LanguageOutline,
  mention: AtOutline,
  read: CheckmarkDoneOutline,
  mark: FlagOutline,
  "rich-text": TextOutline,
  attachment: DocumentAttachOutline,
  "mark-unread": ChatbubbleDotOutline,
  archive: ArchiveOutline,
  unarchive: ArchiveRestoreOutline,
  "clear-history": EraserOutline,
  "mic-off": MicOffOutline,
  "camera-off": VideocamOffOutline,
  speaker: VolumeHighOutline,
  "speaker-off": VolumeMuteOutline,
  "end-call": CallEndOutline,
  "switch-camera": CameraReverseOutline,
  "screen-share": ScreenShareOutline,
  play: PlayOutline,
  pause: PauseOutline,
  expand: ExpandOutline,
  collapse: ContractOutline,
  "zoom-in": ZoomInOutline,
  "zoom-out": ZoomOutOutline,
  rotate: RotateOutline,
  group: PeopleCircleOutline,
  admin: ShieldCheckmarkOutline,
  "remove-member": PersonRemoveOutline,
  "transfer-owner": KeyOutline,
  silence: ChatbubbleOffOutline,
  report: AlertOctagonOutline,
  "chevron-up": ChevronUpOutline,
  "chevron-left": ChevronBackOutline,
  keyboard: KeyboardOutline,
  "mini-app": AppsOutline,
  // Round 9: concepts every kit drew under a name that meant something else.
  "pin-self": BookmarkOutline,
  diagnostics: BugOutline,
  card: IdCardOutline,
  id: HashOutline,
  "join-request": FileTrayOutline,
  storage: ServerOutline,
} satisfies Record<string, Component>;

export type FlareIconName = keyof typeof flareIcons;
export const flareIconNames = Object.keys(flareIcons) as FlareIconName[];
