#!/usr/bin/env node
/**
 * Generates the English `FlareStrings` preset for the three native kits from
 * `strings/en.json`, the single source — the same shape as `tokens/build.mjs`.
 *
 * Why this exists: the native kits' `FlareStrings` are ~500-field structs whose
 * defaults are Chinese, designed to be overridden by the host. No second
 * language shipped, so a host had nothing to switch *to* and a language setting
 * could not do anything. The Vue kit is fully bilingual, but its message tree is
 * a different vocabulary (only ~14% of leaf names coincide), so it cannot feed
 * the native kits — hence a source of its own.
 *
 * `en.json` is keyed by field name and records, per field, the English string,
 * the Chinese default it was translated from (so a changed default is visible in
 * review) and which kits declare it. A field a kit does not declare is skipped
 * for that kit; the three kits' field sets overlap but are not identical.
 *
 *   node strings/build.mjs            write the presets
 *   node strings/build.mjs --check    fail if the presets are out of date
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const check = process.argv.includes("--check");
const source = JSON.parse(readFileSync(join(here, "en.json"), "utf8"));

const BANNER = "// Generated by strings/build.mjs from strings/en.json — do not edit by hand.";

/**
 * Fields this kit declares.
 *
 * Swift requires named arguments in the order the initialiser declares them, so
 * the iOS list is read out of `FlareStrings.swift` rather than sorted — sorting
 * it alphabetically does not compile. Kotlin's builder and Dart's named
 * parameters do not care, so those stay sorted for a stable diff.
 */
function fieldsFor(kit) {
  const declared = Object.keys(source).filter((f) => source[f].kits.includes(kit));
  if (kit !== "ios") return declared.sort();
  const swift = readFileSync(
    join(root, "packages/ios-im-ui/Sources/FlareIMUI/Tokens/FlareStrings.swift"),
    "utf8",
  );
  const init = swift.slice(swift.indexOf("public init("));
  const order = [...init.matchAll(/^        (\w+): String = /gm)].map((m) => m[1]);
  const known = new Set(declared);
  const ordered = order.filter((f) => known.has(f));
  const missing = declared.filter((f) => !order.includes(f));
  if (missing.length) {
    throw new Error(`ios: not in FlareStrings.init — ${missing.join(", ")}`);
  }
  return ordered;
}

const swiftLiteral = (s) => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
const kotlinLiteral = (s) =>
  `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\$/g, "\\$")}"`;
const dartLiteral = (s) => `'${s.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\$/g, "\\$")}'`;

const targets = [
  {
    kit: "ios",
    path: join(root, "packages/ios-im-ui/Sources/FlareIMUI/Tokens/FlareStrings+English.swift"),
    render(fields) {
      const args = fields.map((f) => `            ${f}: ${swiftLiteral(source[f].en)}`).join(",\n");
      return `${BANNER}

import Foundation

public extension FlareStrings {
    /// The kit's component copy in English. Hosts apply it at the root:
    ///
    /// \`\`\`swift
    /// ContentView().flareStrings(.english)
    /// \`\`\`
    ///
    /// The defaults on \`FlareStrings\` stay Chinese; this is the second language,
    /// not a replacement. Fields the source does not cover keep their default.
    static var english: FlareStrings {
        FlareStrings(
${args}
        )
    }
}
`;
    },
  },
  {
    kit: "android",
    path: join(root, "packages/android-im-ui/src/main/kotlin/com/flare/im/ui/FlareStringsEnglish.kt"),
    render(fields) {
      const body = fields.map((f) => `    ${f} = ${kotlinLiteral(source[f].en)}`).join("\n");
      return `${BANNER}

package com.flare.im.ui

/**
 * The kit's component copy in English. Hosts apply it at the root:
 *
 * \`\`\`kotlin
 * CompositionLocalProvider(LocalFlareStrings provides flareStringsEnglish()) { App() }
 * \`\`\`
 *
 * The defaults on [FlareStrings] stay Chinese; this is the second language, not a
 * replacement. Fields the source does not cover keep their default.
 */
fun flareStringsEnglish(): FlareStrings = FlareStrings {
${body}
}
`;
    },
  },
  {
    kit: "flutter",
    path: join(root, "packages/flutter-im-ui/lib/src/tokens/flare_strings_english.dart"),
    render(fields) {
      const body = fields.map((f) => `  ${f}: ${dartLiteral(source[f].en)},`).join("\n");
      return `${BANNER}

import 'flare_strings.dart';

/// The kit's component copy in English. Hosts apply it at the root:
///
/// \`\`\`dart
/// FlareStringsScope(strings: flareStringsEnglish, child: app)
/// \`\`\`
///
/// The defaults on [FlareStrings] stay Chinese; this is the second language, not
/// a replacement. Fields the source does not cover keep their default.
const FlareStrings flareStringsEnglish = FlareStrings(
${body}
);
`;
    },
  },
];

let stale = 0;
for (const t of targets) {
  const fields = fieldsFor(t.kit);
  const next = t.render(fields);
  let current = null;
  try {
    current = readFileSync(t.path, "utf8");
  } catch {
    /* not written yet */
  }
  if (current === next) {
    console.log(`${t.kit}: up to date (${fields.length} fields)`);
    continue;
  }
  if (check) {
    console.error(`${t.kit}: OUT OF DATE — run \`node strings/build.mjs\``);
    stale += 1;
    continue;
  }
  writeFileSync(t.path, next);
  console.log(`${t.kit}: wrote ${fields.length} fields → ${t.path.slice(root.length + 1)}`);
}
if (stale) process.exit(1);
