// GENERATED by tokens/build.mjs. Logical CSS pixels, measured inside the container.
export const flareLayout = {
  "avatarSize": 44,
  "headerHeight": 60,
  "leftPanel": 320,
  "rightPanel": 300,
  "sessionItemHeight": 72,
  "dualPaneMinWidth": 720,
  "triplePaneMinWidth": 1100,
  "chatMinWidth": 360,
  "touchTarget": 48
} as const;
export function paneCount(width: number, hasDetail = false, textScale = 1,
  listWidth: number = flareLayout.leftPanel, detailWidth: number = flareLayout.rightPanel): number {
  const chat = flareLayout.chatMinWidth * Math.min(2, Math.max(1, textScale));
  const list = Math.max(0, listWidth), detail = Math.max(0, detailWidth);
  if (hasDetail && width >= flareLayout.triplePaneMinWidth && width >= list + detail + chat + 2) return 3;
  if (width >= flareLayout.dualPaneMinWidth && width >= list + chat + 1) return 2;
  return 1;
}
