// Prototype-only: simulated microphone and playback, shared with the existing composer.
(()=>{
const button=document.querySelector('[data-panel="voice"]');
const paths={back:'M3 4h18v16H3ZM6 8h.01M10 8h.01M14 8h.01M18 8h.01M6 12h.01M10 12h.01M14 12h.01M18 12h.01M8 16h8',trash:'M4 6h16M9 6V3h6v3M6 6v15h12V6M10 10v7M14 10v7',pause:'M8 5v14M16 5v14',play:'m8 5 11 7-11 7Z'};
const svg=n=>paths[n]?'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="'+paths[n]+'"/></svg>':icon3(n);
const view=document.createElement('section');view.className='voice-inline';view.setAttribute('aria-label','语音录制');view.innerHTML='<div class="voice-main"><button data-v="back" aria-label="返回键盘并删除录音" title="返回键盘并删除录音">'+svg('back')+'</button><button data-v="primary" class="voice-primary"></button><span class="voice-duration">00:00</span><div class="voice-track" aria-label="录音波形">'+Array.from({length:60},(_,i)=>'<i style="--h:'+(5+Math.abs(Math.sin(i*1.7))*22)+'px;--d:-'+(i%8)*.1+'s"></i>').join('')+'<input type="range" min="0" max="100" value="0" aria-label="试听进度" disabled></div><button data-v="resume" aria-label="继续录音" title="继续录音">'+svg('mic')+'</button><button data-v="trash" aria-label="删除录音" title="删除录音">'+svg('trash')+'</button><button data-v="send" class="voice-send" aria-label="发送语音" title="发送语音">'+svg('plane')+'</button></div><div class="voice-helper" role="status"><span class="voice-dot"></span><span class="voice-label"></span><small>原型模拟 · 不采集声音</small></div><div class="voice-confirm" hidden><span>删除这段录音？</span><button data-v="keep">保留</button><button data-v="delete">删除</button></div>';
dock.append(view);const q=s=>view.querySelector(s),b=n=>q('[data-v="'+n+'"]');let phase='idle',seconds=0,position=0,playing=false,timer=null,playTimer=null,active=false,failed=false,attempts=0,warning='';
// One quiet row. Secondary actions are available from the overflow control.
const main=q('.voice-main');
const clip=document.createElement('div');clip.className='voice-clip';
main.insertBefore(clip,q('.voice-duration'));clip.append(q('.voice-track'),q('.voice-duration'));
const more=document.createElement('button');more.className='voice-more';more.innerHTML=svg('more');more.setAttribute('aria-label','更多语音操作');more.setAttribute('aria-expanded','false');more.title='更多语音操作';main.insertBefore(more,b('send'));
const menu=document.createElement('div');menu.className='voice-menu';menu.hidden=true;menu.setAttribute('aria-label','语音操作');
for(const [name,label] of [['trash','删除录音']]){const btn=b(name);btn.insertAdjacentHTML('beforeend','<span>'+label+'</span>');menu.append(btn)}view.append(menu);main.insertBefore(b('resume'),more);b('resume').classList.add('voice-resume');
function dismissMenu(){menu.hidden=true;more.setAttribute('aria-expanded','false')}
more.onclick=()=>{menu.hidden=!menu.hidden;more.setAttribute('aria-expanded',String(!menu.hidden))};
view.addEventListener('click',e=>{if(e.target.closest('.voice-menu button'))dismissMenu()});
document.addEventListener('pointerdown',e=>{if(!view.contains(e.target))dismissMenu()});
q('.voice-helper small').remove();
const time=n=>String(Math.floor(n/60)).padStart(2,'0')+':'+String(Math.floor(n%60)).padStart(2,'0');
function stopPlay(){playing=false;clearInterval(playTimer)}
function paint(){const recording=phase==='recording',paused=phase==='paused';button.classList.toggle('has-voice',seconds>0&&!active);button.setAttribute('aria-expanded',String(active));dock.classList.toggle('voice-mode',active);q('.voice-duration').textContent=time(playing?position:seconds);q('.voice-track').className='voice-track '+(recording?'is-recording':paused?'is-paused':'');q('.voice-track input').disabled=!paused;q('.voice-track input').value=seconds?position/seconds*100:0;q('.voice-track input').setAttribute('aria-valuetext',time(position)+' / '+time(seconds));q('.voice-track').querySelectorAll('i').forEach((el,i)=>el.classList.toggle('played',position/seconds>i/60));b('primary').innerHTML=svg(recording?'pause':paused?(playing?'pause':'play'):'mic');b('primary').classList.toggle('is-recording',recording);b('primary').setAttribute('aria-label',recording?'暂停录音':paused?(playing?'暂停试听':'试听录音'):'开始录音');b('primary').title=b('primary').getAttribute('aria-label');view.dataset.phase=phase;b('send').hidden=!paused;b('resume').hidden=!paused;b('resume').disabled=seconds>=120;b('trash').disabled=seconds===0;b('send').disabled=!paused||!allowed3();q('.voice-dot').hidden=!recording;q('.voice-label').textContent=warning||(recording?'正在录音':paused?(playing?'正在模拟试听':failed?'发送失败，录音已保留，可重试':'已暂停，可试听'):'点击麦克风开始录音');q('.voice-helper').classList.toggle('voice-error',!!warning||failed);view.classList.toggle('voice-has-error',!!warning||failed);view.classList.toggle('is-live',recording);more.disabled=seconds===0;}
function pause(){clearInterval(timer);stopPlay();phase=seconds>=1?'paused':'idle';if(seconds<1)warning='录音不足 1 秒，请重新开始';paint()}
function record(){if(!policy9().edit){notify(policy9().message);return}if($('#network').value==='permission'){warning='麦克风权限未开启 · 切换模拟状态后重试';paint();return}if(seconds>=120){warning='已达到 2 分钟上限，可试听后发送';paint();return}warning='';failed=false;stopPlay();phase='recording';const start=performance.now(),base=seconds;timer=setInterval(()=>{seconds=Math.min(120,base+(performance.now()-start)/1000);if(seconds>=120)pause();paint()},120);paint()}
function playback(){if(playing){stopPlay();paint();return}if(position>=seconds)position=0;playing=true;const start=performance.now(),base=position;playTimer=setInterval(()=>{position=Math.min(seconds,base+(performance.now()-start)/1000);if(position>=seconds)stopPlay();paint()},100);paint()}
function park(){dismissMenu();if(phase==='recording')pause();stopPlay();active=false;paint();update();}
function clearRecording(){clearInterval(timer);stopPlay();phase='idle';seconds=0;position=0;warning='';failed=false;attempts=0;q('.voice-confirm').hidden=true;dismissMenu();}
function returnKeyboard(){clearRecording();active=false;paint();update();editor.focus();notify('已返回键盘，录音已删除');}
function open(){if(busy||!policy9().edit){notify(policy9().message||'当前不可编辑');return}closeTray();expanded(false);active=true;paint()}
button.onclick=open;
b('back').onclick=returnKeyboard;b('primary').onclick=()=>phase==='recording'?pause():phase==='paused'?playback():record();b('resume').onclick=record;
b('trash').onclick=()=>{if(phase==='recording')pause();stopPlay();q('.voice-confirm').hidden=false;paint()};b('keep').onclick=()=>q('.voice-confirm').hidden=true;b('delete').onclick=()=>{clearInterval(timer);stopPlay();phase='idle';seconds=0;position=0;warning='';failed=false;attempts=0;q('.voice-confirm').hidden=true;park()};
q('input').oninput=e=>{stopPlay();position=seconds*Number(e.target.value)/100;paint()};
b('send').onclick=()=>{if(phase!=='paused'||!allowed3())return;stopPlay();if($('#network').value==='failed'&&attempts++===0){failed=true;paint();return}addMessage('<div class="voice-bubble">'+svg('play')+'<span>'+Math.max(1,Math.round(seconds))+'″</span></div><small>语音原型 · 模拟发送</small>',false);phase='idle';seconds=0;position=0;failed=false;attempts=0;warning='';park();notify('已模拟发送语音，文字草稿保留')};
const closeBefore=closeTray;closeTray=function(){if(active)park();closeBefore()};
$('#network').addEventListener('change',()=>{if(active&&phase==='recording')pause();warning='';paint()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&active){e.preventDefault();park()}});window.addEventListener('pagehide',()=>{clearInterval(timer);stopPlay()});
const scene=document.createElement('button');scene.textContent='语音消息';const sub=document.createElement('span');sub.textContent='极简单行 · 语音草稿 ↗';scene.append(sub);scene.onclick=open;$('.states').append(scene);
const note=document.createElement('p');note.style.cssText='font-size:11px;line-height:1.7';note.textContent='进入语音后点击开始录音；暂停后可直接继续录音或试听。点击键盘立即停止并删除录音，文字草稿不受影响。录音与试听仅为模拟。';$('.intro').append(note);paint();
})();
